#!/usr/bin/env bash

curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:i_cri_cn
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:jandan_net
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:jiecao_fm
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:m_huanqiu_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:moviesoon_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:pansci_asia
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_adaymag_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_chinanews_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_ifanr_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_ifeng_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_jrj_com_cn
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_missevan_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_people_com_cn
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_pingwest_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_qianzhan_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_zaobao_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_oushinet_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_ettoday_net

curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:cn_nikkei_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_ltaaa_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_wumaow_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_ftchinese_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_hanjucc_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_hanjumi_net
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_jiemian_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_thepaper_cn
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_chinatimes_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_stnn_cc
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_cankaoxiaoxi_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_yicai_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_bjd_com_cn
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_mtime_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:news_17173_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_meizitu_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_7y7_com
curl http://localhost:6888/schedule.json -d project=News -d spider=spider:news:www_4908_cn