# coding: utf-8

SPIDER_NAME = "spider:news:wechat"
COMMENT_SPIDER_NAME = "spider:news:comment:wechat"
CRAWL_SOURCE = u"微信公众号"

CATEGORIES = [
    {
        "oid": "iwaimei",
        "name": u"外媒看天朝",
        "channel_id": 29,
        "frequency": 60*5,
        "description": u"外媒如何看中国？不用翻墙，这里都有。",
        "image": "",
        "url": "",
    },
    {
        "oid": "geekpark",
        "name": u"极客公园",
        "channel_id": 4,
        "frequency": 60*5,
        "description": u"科技创新者的大本营。汇聚优秀的产品报道、评测视频和高质量的线下活动。",
        "image": "",
        "url": "",
    },
    {
        "oid": "TechWeb",
        "name": u"TechWeb",
        "channel_id": 22,
        "frequency": 60*6,
        "description": u"TechWeb专注于互联网消费领域，每日专业提供互联网产品、智能设备及互联网服务等方面的最新资讯。",
        "image": "",
        "url": "",
    },
    {
        "oid": "i-yiou",
        "name": u"亿欧网",
        "channel_id": 22,
        "frequency": 60*6,
        "description": u"亿欧网，驱动创业创新，助力传统产业转型升级。",
        "image": "",
        "url": "",
    },
    {
        "oid": "ifanr",
        "name": u"爱范儿",
        "channel_id": 4,
        "frequency": 60*4,
        "description": u"关注这个时代最好的产品。",
        "image": "",
        "url": "",
    },
    {
        "oid": "iheima",
        "name": u"i黑马",
        "channel_id": 22,
        "frequency": 60*5,
        "description": u"每一个有创业精神的人都在关注的订阅号。专注创业故事、实战干货和行业数据的生产，偶尔吐槽一下这个变幻莫测的创投圈。",
        "image": "",
        "url": "",
    },
    {
        "oid": "wow36kr",
        "name": u"36氪",
        "channel_id": 22,
        "frequency": 60*5,
        "description": u"36氪(36Kr.com)是中国领先的科技新媒体，我们报道最新的互联网科技新闻以及最有潜力的互联网创业企业。",
        "image": "",
        "url": "",
    },
    {
        "oid": "gaojigou",
        "name": u"搞机者",
        "channel_id": 4,
        "frequency": 60*6,
        "description": u"夜观科技动态，洞察数码产品，只为绞尽脑汁编好图文。图文阅读量高了，谢天谢地谢粉丝，写砸了，被喷删稿还封号。顶三五载自媒体头衔，只为挣七八吊养老钱。",
        "image": "",
        "url": "",
    },
    {
        "oid": "ichuangyebang",
        "name": u"创业邦杂志",
        "channel_id": 22,
        "frequency": 60*6,
        "description": u"创业邦唯一官方微信，中国最权威的创业服务平台。旗下有创业邦杂志、创业邦网站、孵化器等服务。我们是中国最有影响力的创新创业产品展示活动 DEMO CHINA「创新中国」主办方。",
        "image": "",
        "url": "",
    },
    {
        "oid": "apptoday",
        "name": u"科技每日推送",
        "channel_id": 4,
        "frequency": 60*6,
        "description": u"原“App每日推送”官方公众号，专注科技生活的媒体，讲述手机数码、App软件、智能设备的资讯、技巧和故事，并提供手机保修状态、维修估价、回收估价、山寨机鉴别和维修点位置等的查询功能！",
        "image": "",
        "url": "",
    },
    {
        "oid": "huxiu_com",
        "name": u"虎嗅网",
        "channel_id": 22,
        "frequency": 60*6,
        "description": u"有视角的商业资讯交流平台",
        "image": "",
        "url": "",
    },
    {
        "oid": "seweekly",
        "name": u"南都娱乐周刊",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"中国娱乐第一刊、《南都娱乐周刊》",
        "image": "",
        "url": "",
    },
    {
        "oid": "dushemeishaonv",
        "name": u"毒舌美少女",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"吐槽娱乐圈！",
        "image": "",
        "url": "",
    },
    {
        "oid": "juziyule",
        "name": u"橘子娱乐",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"橘子娱乐™ 给你快乐！橘子娱乐只提供最新鲜、最时髦、最有趣的娱乐内容。我们拒绝平淡无奇的流水账，更鄙视毫不走心的娱乐态度。好内容值得被分享。",
        "image": "",
        "url": "",
    },
    {
        "oid": "jinyingwang",
        "name": u"芒果TV",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"芒果TV，看见好时光！湖南广电旗下唯一视频网站，最全最新芒果快乐独家送达。",
        "image": "",
        "url": "",
    },
    {
        "oid": "CommentBrother",
        "name": u"娱乐星扒客",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"发布第一手明星幕后猛料，及娱乐评论。",
        "image": "",
        "url": "",
    },
    {
        "oid": "entifengvip",
        "name": u"凤凰八卦",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"扒得更深，揭得更透，更多不可说的秘事，尽在“凤凰八卦”，添加免费阅读。",
        "image": "http://wx.qlogo.cn/mmhead/Q3auHgzwzM4icGxFMN5Q87cGwyNaS4DVDo9cIQ7Xia90J5gxoQjsfdibw/0",
        "url": "",
    },
    {
        "oid": "bbbbaye",
        "name": u"圈内扒爷",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"娱乐有理，吐槽无罪。",
        "image": "http://wx.qlogo.cn/mmhead/Q3auHgzwzM4kpUoBB91jMGaxvjKVbON0odqpJI5iarQkRicS7eDY3iafA/0",
        "url": "",
    },
    {
        "oid": "yeshoupaiyule",
        "name": u"野兽派娱乐",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"有假冒的请注意！搜索【yeshoupaiyule】能找到的才是正版野兽派娱乐~~",
        "image": "http://wx.qlogo.cn/mmhead/Q3auHgzwzM5gic0x1T8On4H1qZGReM317WUw3Rm3xDE7cEOFEbiab13w/0",
        "url": "",
    },
    {
        "oid": "yuwenyule123",
        "name": u"娱文愚乐",
        "channel_id": 3,
        "frequency": 60*6,
        "description": u"娱记资深编辑，不求扒得深，但求看得彻。",
        "image": "http://wx.qlogo.cn/mmhead/Q3auHgzwzM5hABfBuICNADFuredy8ibH0GKHCBaSQpQuryp0I1j9Eaw/0",
        "url": "",
    },
    {
        "oid": "mymoney888",
        "name": u"钱眼",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"你不理财，财不理你！怎样管好自己的钱，让它尽可能地钱生钱，扬子晚报财经微信为您提供独特的理财眼光和实用技巧，哪个“宝宝”收益高，跟我炒股不亏钱，买房买金谁保险，一应俱全快来瞧！",
        "image": "",
        "url": "",
    },
    {
        "oid": "wuxiaobopd",
        "name": u"吴晓波频道",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"“吴晓波频道”是财经作家吴晓波在微信平台上进行内容发布的自媒体，涵盖视频、专栏和测试。视频部分与爱奇艺合作，每周四推出。",
        "image": "",
        "url": "",
    },
    {
        "oid": "cnfol-com",
        "name": u"中金在线",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"独特、深度、有趣，全方位解读与你相关的财经事件，有投资高手在“聊股解疑”与你互动，还有股票、贵金属、外汇的最新行情查询。",
        "image": "",
        "url": "",
    },
    {
        "oid": "zepinghongguan",
        "name": u"泽平宏观",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"预判经济形势，解读公共政策，提供及时信息，推送专业报告。",
        "image": "",
        "url": "",
    },
    {
        "oid": "gushequ",
        "name": u"股社区",
        "channel_id": 20,
        "frequency": 60*6,
        "description": u"",
        "image": "",
        "url": "",
    },
    {
        "oid": "kongfuf",
        "name": u"功夫财经",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"功夫财经作为中国财经集体自媒体第一平台,集合了李大霄、马光远、王福重、时寒冰、胡润以及财经脱口秀达人琢磨先生等各路大侠,每天以最独到、最个性、最鲜活的视角,解读财经事件,透视财富生活.",
        "image": "",
        "url": "",
    },
    {
        "oid": "jiemuzhe518",
        "name": u"揭幕者",
        "channel_id": 20,
        "frequency": 60*6,
        "description": u"中国最牛十大原创证券自媒体,全国首位点击破亿的财经博客,全国最有价值的财经自媒体!请记住老揭唯一ID号 jiemuzhe518 其余都是假的, 每日免费提供操盘必读、涨停揭秘、龙虎榜等独家炒股猛料!中国1.5亿股民每日...",
        "image": "",
        "url": "",
    },
    {
        "oid": "hkstocks",
        "name": u"港股那点事",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"格隆汇旗下公众号.分享和探讨港股、美国中概股以及少量估值确有吸引力之A股的投资线索、投资机会与投资心得.",
        "image": "",
        "url": "",
    },
    {
        "oid": "xueqiujinghua",
        "name": u"雪球",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"雪球为社交投资网络雪球(xueqiu.com)唯一官方账号,每日推送雪球内有趣、有料、有价值的原创文章,不定期发放各种福利.下载雪球APP请到各大应用市场搜索“雪球”.",
        "image": "",
        "url": "",
    },
    {
        "oid": "p2pguancha",
        "name": u"P2P观察",
        "channel_id": 7,
        "frequency": 60*6,
        "description": u"P2P网贷第一微信.资深媒体人和资深观察家联手巨献,为您解读P2P网贷最新资讯、政策动态、大咖解读,互联网金融,我们聚焦P2P网贷.",
        "image": "",
        "url": "",
    },
    {
        "oid": "pptvsports",
        "name": u"PPTV体育",
        "channel_id": 6,
        "frequency": 60*6,
        "description": u"PPTV第1体育官方微信",
        "image": "",
        "url": "",
    },
    {
        "oid": "yangyitalk",
        "name": u"杨毅侃球",
        "channel_id": 6,
        "frequency": 60*6,
        "description": u"篮球评论员,中央电视台篮球解说顾问,体坛周报副总编.",
        "image": "",
        "url": "",
    },
    {
        "oid": "jianxiangtalk",
        "name": u"黄健翔谈",
        "channel_id": 6,
        "frequency": 60*6,
        "description": u"黄健翔“玩转”足球的自媒体阵地,语音点评与图文故事交织,辅以黄健翔的个人动态,构架起专属黄健翔的个人频道.",
        "image": "",
        "url": "",
    },
    {
        "oid": "qiudingzuqiu",
        "name": u"球叮足球",
        "channel_id": 6,
        "frequency": 60*6,
        "description": u"球叮,和朋友一起享受足球~",
        "image": "",
        "url": "",
    },
    {
        "oid": "titansports",
        "name": u"体坛周报",
        "channel_id": 6,
        "frequency": 60*6,
        "description": u"中国最专业、最权威、期发量最大的体育报纸",
        "image": "",
        "url": "",
    },
    {
        "oid": "chuanyiaa",
        "name": u"最潮穿衣搭配",
        "channel_id": 10,
        "frequency": 60*6,
        "description": u"三分长相七分打扮;还在愁怎么穿衣服么?还在愁怎么搭配么?点击下方的”关注“;和小编一起来学习穿衣搭配吧!",
        "image": "",
        "url": "",
    },
    {
        "oid": "jjzy80",
        "name": u"教你扎头发",
        "channel_id": 10,
        "frequency": 60*6,
        "description": u"发型对了;怎么穿都美!爱折腾头发就关注我吧!",
        "image": "",
        "url": "",
    },
    {
        "oid": "scp288",
        "name": u"奢侈品",
        "channel_id": 10,
        "frequency": 60*6,
        "description": u"无意义的奢侈是浪费,真正的奢侈是对生活的追求.",
        "image": "",
        "url": "",
    },
    {
        "oid": "shishangiii",
        "name": u"全球时尚",
        "channel_id": 10,
        "frequency": 60*6,
        "description": u"全球顶级时尚集聚地,每日发布最潮最前沿的时尚资讯!",
        "image": "",
        "url": "",
    },
    {
        "oid": "fashion_163",
        "name": u"网易时尚",
        "channel_id": 10,
        "frequency": 60*6,
        "description": u"网易时尚,专注提供时尚资讯、解析行业现状,输送优质时尚价值观.内容涵盖时尚、美容、情感、艺术4大版块,致力于做有态度的时尚生活门户.",
        "image": "",
        "url": "",
    },
    {
        "oid": "OKSimsimi",
        "name": u"英国那些事儿",
        "channel_id": 29,
        "frequency": 60*6,
        "description": u"事儿君告诉你在全世界发生的各种奇奇怪怪最搞最有意思的大小事",
        "image": "",
        "url": "",
    },
    {
        "oid": "cnchktv",
        "name": u"香港传真",
        "channel_id": 29,
        "frequency": 60*6,
        "description": u"真实传递香港声音,聚焦香江热点事件,带您全方位见识香港.中国新华电视控股有限公司(HK.8356)出品.",
        "image": "",
        "url": "",
    },
    {
        "oid": "collegedaily",
        "name": u"北美留学生日报",
        "channel_id": 29,
        "frequency": 60*6,
        "description": u"中国最大的独立留学新媒体,集杂志、网站、app于一身的国际教育新媒体平台.讲述留学生自己的故事,分享有趣而真实的留学生活,发布客观真实的留学资讯,中立、真实、有味道!官方网站:www.CollegeDaily.cn",
        "image": "",
        "url": "",
    },
    {
        "oid": "lrtvjkysq",
        "name": u"健康一身轻",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"辽宁广播电视台都市频道《健康一身轻》栏目.",
        "image": "",
        "url": "",
    },
    {
        "oid": "zyshiliao",
        "name": u"中医食疗养生",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"年少不养生,老来养医生.最好的医生是自己,最好的医院是厨房,最好的药物是饮食,最好的疗效是坚持.",
        "image": "",
        "url": "",
    },
    {
        "oid": "zuijiankang100",
        "name": u"健康最重要",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"爱自己才能爱家人!更健康才能更坚强!",
        "image": "",
        "url": "",
    },
    {
        "oid": "sushiwenhua",
        "name": u"素食",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"中国素食文化传播网 官方微信平台 http://www.veg520.com/ 弘扬素食文化,传播环保理念,维护生命健康,提升人类品质!",
        "image": "",
        "url": "",
    },
    {
        "oid": "LT0385",
        "name": u"生命时报",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"☆人民日报主管,环球时报主办,一份具有国际视野的大众健康周报. ☆每天教你一看就懂、一学就会、一点就通、一用就灵的养生知识,做你值得信赖的“家庭医生”.",
        "image": "",
        "url": "",
    },
    {
        "oid": "ijiankang",
        "name": u"健康小贴士",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"你的贴身健康小贴士!分享健康的生活方式、健康饮食、美容养颜、美丽攻略、心理健康等.崇尚健康生活,就关注“健康小贴士”吧!",
        "image": "",
        "url": "",
    },
    {
        "oid": "health39net",
        "name": u"39健康网",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"www.39.net 中国专业健康资讯门户网站.提供最专业、完善的健康信息服务,包括疾病,保健,健康新闻,专家咨询等服务.",
        "image": "",
        "url": "",
    },
    {
        "oid": "yxj-huxi",
        "name": u"医学界呼吸频道",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"为您提供呼吸科最新资讯~~",
        "image": "",
        "url": "",
    },
    {
        "oid": "shyjkb",
        "name": u"生活与健康报",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"依靠浙江省医学会各专科分会的优质专家资源,普及医药学和科学生活知识,倡导健康文明的生活方式,提升公众医学科学素养.",
        "image": "",
        "url": "",
    },
    {
        "oid": "yxj-erke",
        "name": u"医学界儿科频道",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"医学界儿科频道面向广大儿科医护人员和年轻父母,提供会议动态、学术资讯、专家访谈、科普知识等.",
        "image": "",
        "url": "",
    },
    {
        "oid": "yxj-endo",
        "name": u"医学界内分泌频道",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"医学界内分泌频道,面向全国的内分泌医生、全科医生、大内科医生提供内分泌领域的学术资讯、专家采访、最新指南、典型病例,并提供内分泌科普知识. 《医学界》是面向全国医者的综合性职业生活全媒体,服务医者职业...",
        "image": "",
        "url": "",
    },
    {
        "oid": "DingXiangYiSheng",
        "name": u"丁香医生",
        "channel_id": 24,
        "frequency": 60*6,
        "description": u"国内最大的医学网站丁香园旗下的科普资讯平台.提供可信赖的医疗健康信息和服务,专业医生团队为大众用户科普医学健康知识.关注并回复你想要了解的疾病名称,即可获取最专业的解答.对了,丁香医生的科普辟谣内容...",
        "image": "",
        "url": "",
    },
    {
        "oid": "weixinlukuang",
        "name": u"微信路况",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"最大汽车公众号; 每日为您提供最新的新车资讯、驾车小技巧、保养维修,用车视频演示!查路况、查违章、路况预报、路况定制等服务, 无需下载,只要关注即可使用.",
        "image": "",
        "url": "",
    },
    {
        "oid": "gzwcjs",
        "name": u"玩车教授",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"专业汽车新媒体,专注汽车导购教你如何买车,超过五百万车友关注!24小时提供在线购车咨询.",
        "image": "",
        "url": "",
    },
    {
        "oid": "chezhaocha",
        "name": u"SUV大师",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"您身边的SUV专家!",
        "image": "",
        "url": "",
    },
    {
        "oid": "pcautoweixin1",
        "name": u"太平洋汽车网",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"太平洋汽车网为网友提供新车、导购、评测、用车等最新资讯.",
        "image": "",
        "url": "",
    },
    {
        "oid": "MalaAuto",
        "name": u"麻辣车事",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"为网友提供最独到的汽车评论、深度的行业观察,鲜活的车事资讯和实用的服务信息.",
        "image": "",
        "url": "",
    },
    {
        "oid": "car6080",
        "name": u"汽车知识攻略",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"关注我就等于关注一本汽车杂志!",
        "image": "",
        "url": "",
    },
    {
        "oid": "chetuteng-com",
        "name": u"车图腾",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"车图腾,让你涨姿势的汽车自媒体.专注有意思的干货汽车相关知识分享,包括车企车型、行业数据、购车用车、汽车媒体与车企营销观察等.",
        "image": "",
        "url": "",
    },
    {
        "oid": "t139com",
        "name": u"T139改装网",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"与汽车改装爱好者分享最新的改装资讯及案例",
        "image": "",
        "url": "",
    },
    {
        "oid": "zhinengqiche",
        "name": u"智驾时代",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"科技视角、极客精神,智驾传媒是拥有智能汽车网(AutoR.com.cn)、《AutoR智驾》杂志、微信平台(zhinengqiche)和智能汽车展会的全媒体平台.R是Robot一词的缩写,AutoR意指智能汽车.",
        "image": "",
        "url": "",
    },
    {
        "oid": "www315che",
        "name": u"中国汽车消费网",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"买车用车、快速查车、在线问答!最具价值的汽车微信!",
        "image": "",
        "url": "",
    },
    {
        "oid": "emaonews",
        "name": u"一猫汽车资讯",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"一猫汽车网是一家专注于汽车(包括平行进口车)销售及消费,并旨在解决用户“选啥车、哪家买、啥价买”3大困惑的大型电子商务网站.一猫汽车网致力为用户提供线上到线下;售前到售后的全程购车、用车服务.",
        "image": "",
        "url": "",
    },
    {
        "oid": "qichexiu",
        "name": u"汽车秀",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"汽车秀(qichexiu) 汽车秀,秀汽车!购车省钱秘诀,车辆保养知识,专业汽车测评,独特汽车点评,尽在汽车秀!一切汽车相关问题,欢迎后台实名(姓名+单位+手机)交流.",
        "image": "",
        "url": "",
    },
    {
        "oid": "CarLike",
        "name": u"汽车爱好者",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"最具价值的汽车新媒体.全国最大车迷俱乐部,汽车行业风向标.汽车爱好者的乐园.看车、玩车、用车,一切尽在汽车爱好者!",
        "image": "",
        "url": "",
    },
    {
        "oid": "myxcar",
        "name": u"爱卡汽车",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"爱卡汽车官方微信,从此您可以在微信上找车型、看热帖、读资讯,还能参加各种好玩的活动.",
        "image": "",
        "url": "",
    },
    {
        "oid": "qicheboss",
        "name": u"车头条",
        "channel_id": 5,
        "frequency": 60*6,
        "description": u"为您分享国内外最新的:汽车资讯、汽车新闻、汽车改装、汽车视频、跑车等...",
        "image": "",
        "url": "",
    },
    {
        "oid": "qzjy511314",
        "name": u"亲子教育-幼儿教育、早教胎教育儿",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"打造最专业的亲子中心,每天推送亲子教育,早教胎教专业知识和技巧经验,同时有亲子专家在线解答大家的问题.",
        "image": "",
        "url": "",
    },
    {
        "oid": "yuema2013",
        "name": u"粥悦悦",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"粥悦悦,绘本漫画家、畅销书作家,二胎妈妈.出版物:《悦妈怀孕日记》、《悦妈成长记》、《小花生米在长大》、《悦妈这一家》、《二宝驾到!》等.",
        "image": "",
        "url": "",
    },
    {
        "oid": "kidsfood",
        "name": u"宝宝餐餐见",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"宝宝的每一餐,是妈妈表达爱最好的机会.妈妈的味道,是健康,是营养,是美味.和我们一起,按宝宝月龄做辅食,做儿童餐,精选食材做营养搭配,让宝宝身体棒棒嗒!出得了厅堂的妈妈会多一项本领哦!",
        "image": "",
        "url": "",
    },
    {
        "oid": "weqinzi0",
        "name": u"微亲子",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"相信各位妈妈在育儿这条路上遇到过很多磕磕碰碰的问题,并且很多时候因为宝宝因为孩子让你很苦恼,感到无助,困惑 … 关注微亲子,在这里可以找到解决问题的答案和方法,因为育儿路上你不是一个人在战斗;加入辣妈...",
        "image": "",
        "url": "",
    },
    {
        "oid": "zaojiaobaby",
        "name": u"早教网",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"早教网官方微博.最全的专业早教机构.专为0-4岁宝宝家庭提供早教资讯.100万家庭选择早教服务. 提供胎教、婴幼儿早期教育、早教理念、早教方法、早教建议等专业知识;为宝宝早教提供针对性指导和建议.",
        "image": "",
        "url": "",
    },
    {
        "oid": "MotherClassroom",
        "name": u"辣妈教室",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"国内影响力最大的母婴类微信公众平台,定位于0——13岁孩子的妈妈群体,为您介绍最全面的育儿知识,教育知识,健康养生知识,美容瘦身秘笈,分享女性人生修练及购物心得,全方位指引你变身超级辣妈.时尚女人界最...",
        "image": "",
        "url": "",
    },
    {
        "oid": "zgjyzx",
        "name": u"中国教育在线",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"中国教育在线公众平台立志于分享优秀的教育信息,让我们一起关爱孩子,关爱下一代的健康成长!!",
        "image": "",
        "url": "",
    },
    {
        "oid": "jtjy567",
        "name": u"家庭教育",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"父母是孩子最好的老师,如果你自己不够优秀,如何给孩子更好的教育呢?现在就开始提升自己,让您的孩子快人一步!",
        "image": "",
        "url": "",
    },
    {
        "oid": "qinziriji",
        "name": u"母婴头条",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"关爱妈咪宝贝健康知识,了解最新母婴资讯,让您的宝宝快乐成长.",
        "image": "",
        "url": "",
    },
    {
        "oid": "mama8090",
        "name": u"8090妈妈群",
        "channel_id": 16,
        "frequency": 60*6,
        "description": u"8090妈妈群女性社区平台;如何打击小三、健康交流、情感自传连载、育儿交流、备孕、怀孕、时尚妈妈的互联网社交平台;与辣妈分享生活中点滴;成为现实生活中的最佳闺蜜.",
        "image": "",
        "url": "",
    },
    {
        "oid": "thepapernews",
        "name": u"澎湃新闻",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"有内涵的时政新媒体",
        "image": "",
        "url": "",
    },
    {
        "oid": "cctvnewscenter",
        "name": u"央视新闻",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"中央电视台新闻中心公众号,提供时政、社会、财经、体育、突发等新闻信息以及天气、路况、视频直播等服务信息.",
        "image": "",
        "url": "",
    },
    {
        "oid": "beijingtimes",
        "name": u"京华时报",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"热点新闻、深度分析、娱乐八卦、搞笑奇葩……我们做得了深度、挖的出独家、卖一手好萌、碎一地节操,只有你想不到的,没有我们做不到的!还没关注?你out了!",
        "image": "",
        "url": "",
    },
    {
        "oid": "BJCB96101",
        "name": u"北京晨报",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"北京晨报【新闻热线:】010-96101(市话).",
        "image": "",
        "url": "",
    },
    {
        "oid": "NF_Daily",
        "name": u"南方日报",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"高度决定影响力",
        "image": "",
        "url": "",
    },
    {
        "oid": "hqsbwx",
        "name": u"环球时报",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"报道多元世界 解读复杂中国",
        "image": "",
        "url": "",
    },
    {
        "oid": "guanchacn",
        "name": u"观察者网",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"观察者网,智库与专业新闻媒体的完美结合.",
        "image": "",
        "url": "",
    },
    {
        "oid": "nbdnews",
        "name": u"每日经济新闻",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"【新闻决定影响力】",
        "image": "",
        "url": "",
    },
    {
        "oid": "shxw00",
        "name": u"社会新闻观天下",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"关注社会民生、社会法治、社会文化,第一时间直击突发事件,新闻事件的调查者、记录者、守望者.欢迎提供新闻线索!",
        "image": "",
        "url": "",
    },
    {
        "oid": "yzwb20102806",
        "name": u"扬子晚报",
        "channel_id": 2,
        "frequency": 60*6,
        "description": u"新鲜事、有趣事、不平事、离奇事、为难事,欢迎第一时间微信我们哦!",
        "image": "",
        "url": "",
    },
    {
        "oid": "miercn123",
        "name": u"米尔军事网",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"来自腾讯微博认证资料:军事网站,以独特视角报道军事. @米尔军情网",
        "image": "",
        "url": "",
    },
    {
        "oid": "tiexuejunshi",
        "name": u"铁血军事",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"铁血网,基于铁血论坛资讯内容的军事类资讯门户.提供中国军事、世界军事、军事新闻、原创军事评论、军事科技、军事小说、军品装备等全方位的中国军事及世界军事内容.",
        "image": "",
        "url": "",
    },
    {
        "oid": "zgjw_81",
        "name": u"中国军网",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"中央军委批准 中国人民解放军唯一新闻门户网站.",
        "image": "",
        "url": "",
    },
    {
        "oid": "sinamilnews",
        "name": u"新浪军事",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"播报东海,南海最新军情,揭秘热点军事外交事件内幕,对比解放军新式武器和西方性能,再现民国,二战等历史.",
        "image": "",
        "url": "",
    },
    {
        "oid": "military_china",
        "name": u"中华网军事",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"中华网军事是中国访问量最大的军事站点,频道由新闻资讯、品牌栏目、军事图库和军迷生活四大版块组成.中华网军事坚持以独特的视角报道军事事件,受到数百万军迷的关注.",
        "image": "",
        "url": "",
    },
    {
        "oid": "milifengcom",
        "name": u"凤凰网军事频道",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"凤凰网军事频道,是凤凰军事唯一官方公众号.掌握最新的防务新闻,解读最透彻的军事情报,为读者展现全方位的国防评论.领先的话题源自于独立视角,通俗的内容源自于专业精神.欢迎关注.",
        "image": "",
        "url": "",
    },
    {
        "oid": "junshi6",
        "name": u"国际军事网",
        "channel_id": 8,
        "frequency": 60*6,
        "description": u"提供军事新闻 关注国际军事重大新闻及中国军事热点新闻动态",
        "image": "",
        "url": "",
    },
    {
        "oid": "tsjunshi81",
        "name": u"鹰眼图说军事",
        "channel_id": 22,
        "frequency": 60*6,
        "description": u"鹰眼图说军事为大家提供最新全球军事动态,中国武器装备、钓鱼岛和南海局势等最新热点军事新闻及图片资讯.",
        "image": "",
        "url": "",
    },
]
